version: '3'

services:
  db:
    image: postgres:9.6
    container_name: rails_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    container_name: rails_api
    image: minshif
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - .:/minshif
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
