default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # 権限を設定したユーザーを指定
  username: root
  password: "root"
  host: db

development:
  <<: *default
  database: minshif_development

test:
  <<: *default
  database: minshif_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
