default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # 権限を設定したユーザーを指定
  username: root
  password: "root"
  host: db

development:
  <<: *default
  database: minshif_development

test:
  <<: *default
  database: minshif_test

production:
  <<: *default
  database: minshif_production
  username: <%= ENV.fetch('MYSQL_PRODUCTION_USER') %>
  password: <%= ENV.fetch('MYSQL_PRODUCTION_PASSWORD') %>
  host: <%= ENV['MYSQL_PRODUCTION_HOST'] %>